### ISSUE TITLE
Weekly build on 23/05/2020 is broken

### ISSUE THREAD

**Issue by Dazog** [avpnusr/sabnzbd-dev#1]
Weekly build on 23/05/2020 is broken.

https://github.com/sabnzbd/sabnzbd/issues/1458

Can you please leave us a build before on docker?

Incase the weekly doesn't work, that way we can roll back off latest?

**Comment by avpnusr** [comment]
Thanks for the feedback! I will leave some historic builds in the repo on docker-hub

**Comment by avpnusr** [comment]
Hey @Dazog I changed my automated build-system a bit. Now I provide the standard *:latest tag for the weekly build and leave the historic builds with the tag as build-date - e.g. *:03-06-2020.

Hope this helps for the future.
